### ISSUE TITLE
Symfony / Doctrine Compatibility

### ISSUE THREAD

**Issue by thomaskonrad** [metaclass-nl/MetaclassAuthenticationGuardBundle#14]
Hey,

your bundle seems to cover exactly my requirements for brute-force attack blocking in a Symfony2 project.

However, according to Packagist, your bundle requires Symfony ~2.3 and Doctrine DBAL 2.3.*. My project uses Symfony 2.5 and Doctrine DBAL 2.4 and is therefore in theory not compatible with MetaclassAuthenticationGuardBundle - are these hard requirements or has it just not been tested with newer Symfony and Doctrine versions?

It would be nice to have a version that is compatible with current Symfony and Doctrine versions.

Thanks
Thomas

**Comment by metaclass-nl** [comment]
The dependencies of doctrine where removed from *@dev. The thresholds governor bundle still requires doctrine/dbal "~2.3" because i did not look into what fits my own requirements and because with those requirements removed i had no more problems installing *@dev from both bundles on Symfony 2.6 and 2.7. #2DO: test on Symfony 2.3, and 2.8. I don't think it works with 3.0 yet.

With respect to the theory: to be honest i find "~2.3" kind of vague. For example Composer updated my symfony "~2.7" install spontanously to 2.8! Trouble is that i don't want to spend time testing it on 2,4 and 2,5, but i guess it will work so i do not want to exclude them either. 

Nevertheless, i agree the requirements should be more specific so  leave this issue open for now.

**Comment by metaclass-nl** [comment]
The metaclass-nl/tresholds-governor (master) now requires "doctrine/dbal": ">=2.3.4". It may work with older versions but that has not been tested. Also tested with v2.4.4. Manually tested with 2.5.2, but that does not check with respect to depricated features. 

0.3.* versions now require "symfony/symfony": ">=2.3.8,<=2.6",
0.4.* versions require "symfony/symfony": ">=2.6,<3.0-dev".
